docs_dir: docs
pages:
- {!!python/unicode 'Home': !!python/unicode 'Home.md'}
- {!!python/unicode 'Po co ta Wiki': !!python/unicode 'Po-co-ta-Wiki/Po-co-ta-Wiki.md'}
site_dir: wolnepszczoly.github.io
site_name: Wiki Pszczelarstwa Naturalnego
source_dir: wikipn.wiki
theme: united
