site_name: 'Wiki Pszczelarstwa Naturalnego'
source_dir: 'wikipn.wiki'
docs_dir: 'docs'
site_dir: 'wolnepszczoly.github.io'
theme: 'united'

# This must be last element
pages:
    - 'Spis treści': 'Home.md'
    #- 'Link': 'http://wolnepszczoly.org'
